language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
services: postgresql
script:
  - npm test
after_script: # Upload coverage reports
  - COVERALLS_REPO_TOKEN=$coveralls_repo_token yarn run coveralls
addons:
  postgresql: "9.3"
